import { parseAbi } from "viem";

export const makebookAbi = parseAbi([
  // Errors
  "error NotOperator()",
  "error WrongState(uint8 expected, uint8 actual)",
  "error ZeroAddress()",
  "error TooManyFactories()",
  "error FactoryAlreadyRegistered()",
  "error FactoryNotRegistered()",
  "error AlreadyQuoted()",
  "error InvalidTiers()",
  "error NoQuotes()",
  "error CampaignNotOpen()",
  "error DeadlinePassed()",
  "error DeadlineNotInFuture()",
  "error InvalidPayment()",
  "error DuplicateOrder()",
  "error OrderLimitReached()",
  "error DeadlineNotReached()",
  "error NoOrder()",
  "error AlreadyClaimed()",
  "error NotSelectedFactory()",
  "error TransferFailed()",

  // Write functions
  "function registerFactory(address factory, bytes32 profileHash)",
  "function submitQuote(bytes32 quoteHash, (uint32 minQty, uint256 unitPriceWei)[] tiers)",
  "function openCampaign()",
  "function placeOrder(bytes32 variantHash, uint256 maxPrice) payable",
  "function settle()",
  "function claimRefund()",
  "function claimPayout()",

  // Read functions
  "function previewSettlement() view returns (bool feasible, uint256 quoteId, uint256 tierIndex, uint256 clearingPrice, uint256 winnerCount)",
  "function getOrder(address buyer) view returns ((address buyer, bytes32 variantHash, uint256 maxPriceWei, bool refundClaimed))",
  "function getQuote(uint256 quoteId) view returns ((address factory, bytes32 quoteHash, (uint32 minQty, uint256 unitPriceWei)[] tiers))",
  "function ordersLength() view returns (uint256)",
  "function quotesLength() view returns (uint256)",
  "function registeredFactoriesLength() view returns (uint256)",
  "function registeredFactories(uint256) view returns (address)",
  "function isRegisteredFactory(address) view returns (bool)",
  "function factoryProfileHash(address) view returns (bytes32)",
  "function hasQuoted(address) view returns (bool)",
  "function state() view returns (uint8)",
  "function operator() view returns (address)",
  "function manifestHash() view returns (bytes32)",
  "function manifestURI() view returns (string)",
  "function deadline() view returns (uint64)",
  "function settlementFeasible() view returns (bool)",
  "function winningQuoteId() view returns (uint256)",
  "function winningTierIndex() view returns (uint256)",
  "function clearingPrice() view returns (uint256)",
  "function winnerCount() view returns (uint256)",
  "function selectedFactory() view returns (address)",
  "function factoryReceivable() view returns (uint256)",
  "function factoryPayoutClaimed() view returns (bool)",
  "function MAX_ORDERS() view returns (uint256)",
  "function MAX_FACTORIES() view returns (uint256)",
  "function MAX_TIERS() view returns (uint256)",

  // Events
  "event CampaignOpened(bytes32 manifestHash, uint64 deadline)",
  "event FactoryRegistered(address indexed factory, bytes32 profileHash)",
  "event QuoteSubmitted(uint256 indexed quoteId, address indexed factory, bytes32 quoteHash)",
  "event OrderPlaced(address indexed buyer, uint256 maxPrice, bytes32 variantHash)",
  "event CampaignSettled(bool success, uint256 winningQuoteId, uint256 tierIndex, uint256 clearingPrice, uint256 winnerCount)",
  "event RefundClaimed(address indexed buyer, uint256 amount)",
  "event FactoryPayoutClaimed(address indexed factory, uint256 amount)",
]);
