[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "prb-math/=lib/prb-math/src/",
]

[rpc_endpoints]
injectiveEvm = "https://k8s.testnet.json-rpc.injective.network/"

[etherscan]
injectiveEvm = { key = "no-key-needed", url = "https://testnet.blockscout-api.injective.network/api/", chain = 1439 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
